#!/usr/bin/env python3
"""
generate_test_data.py - Genera Dati Test per Upload

Crea file CSV con transito sintetico per testare sistema upload.

Usage:
    python generate_test_data.py

Output:
    test_transit.csv - File CSV con transito
"""

import numpy as np

def generate_transit_csv(
    filename='test_transit.csv',
    period=3.5,
    n_transits=3,
    depth=0.01,
    duration=0.1,
    noise_ppm=1000
):
    """
    Genera file CSV con transito esopianeta.
    
    Args:
        filename: Nome file output
        period: Periodo orbitale [giorni]
        n_transits: Numero transiti
        depth: Profondità transito (ΔF/F)
        duration: Durata transito [giorni]
        noise_ppm: Rumore fotometrico [ppm]
    """
    
    print("="*60)
    print("GENERAZIONE DATI TEST TRANSITO")
    print("="*60)
    print()
    
    # Parametri
    baseline = n_transits * period
    t0 = 2460001.5  # Epoca primo transito
    cadence = 0.5 / 1440  # 30 secondi in giorni
    n_points = int(baseline / cadence)
    
    print(f"Parametri:")
    print(f"  Periodo: {period} giorni")
    print(f"  Transiti: {n_transits}")
    print(f"  Profondità: {depth*100}% = {depth*1e6:.0f} ppm")
    print(f"  Durata: {duration*24:.2f} ore")
    print(f"  Rumore: {noise_ppm} ppm")
    print(f"  Punti: {n_points}")
    print(f"  Baseline: {baseline:.1f} giorni")
    print()
    
    # Genera tempi
    jd = np.linspace(t0, t0 + baseline, n_points)
    
    # Modello transito (box-shaped)
    flux = np.ones(n_points)
    
    for i in range(n_transits):
        t_center = t0 + i * period
        
        # Punti in transito
        in_transit = np.abs(jd - t_center) < duration / 2
        flux[in_transit] = 1 - depth
    
    # Aggiungi rumore Gaussiano
    noise = noise_ppm / 1e6  # ppm → frazione
    flux += np.random.normal(0, noise, n_points)
    
    # Errori (stima)
    flux_err = np.full(n_points, noise)
    
    # Aggiungi alcuni outlier (0.1%)
    n_outliers = int(0.001 * n_points)
    outlier_idx = np.random.choice(n_points, n_outliers, replace=False)
    flux[outlier_idx] += np.random.normal(0, 5*noise, n_outliers)
    
    print(f"Aggiunti {n_outliers} outlier")
    print()
    
    # Salva CSV
    print(f"Salvando {filename}...")
    
    with open(filename, 'w') as f:
        # Header
        f.write("# Test Transit Data\n")
        f.write(f"# Generated by generate_test_data.py\n")
        f.write(f"# Period: {period}d, Depth: {depth*100}%, Noise: {noise_ppm}ppm\n")
        f.write("#\n")
        f.write("JD_UTC, Flux, Flux_err\n")
        
        # Dati
        for j, fl, err in zip(jd, flux, flux_err):
            f.write(f"{j:.6f}, {fl:.6f}, {err:.6f}\n")
    
    print(f"✓ File salvato: {filename}")
    print()
    
    # Statistiche
    print("Statistiche dati:")
    print(f"  Flux medio: {np.mean(flux):.6f}")
    print(f"  Flux std: {np.std(flux)*1e6:.0f} ppm")
    print(f"  Flux min: {np.min(flux):.6f}")
    print(f"  SNR transito: {depth/noise:.1f}")
    print()
    
    print("="*60)
    print("✓ Generazione completata!")
    print("="*60)
    print()
    print(f"Carica {filename} nell'interfaccia AGATA:")
    print("  1. Vai a http://your-server:5000/agata/exoplanets/")
    print("  2. Seleziona 'Upload File Osservazioni'")
    print("  3. Carica il file generato")
    print()


if __name__ == "__main__":
    # Genera file test
    generate_transit_csv(
        filename='test_transit.csv',
        period=3.5,
        n_transits=5,
        depth=0.01,
        duration=0.12,
        noise_ppm=800
    )
    
    # Genera anche versione solo mag (no errori)
    print("\n" + "="*60)
    print("GENERAZIONE VERSIONE SOLO MAGNITUDINI")
    print("="*60)
    print()
    
    # Parametri
    jd = np.linspace(2460001, 2460005, 500)
    period = 2.5
    t0 = 2460001.8
    duration = 0.08
    depth = 0.008
    
    # Flusso normalizzato
    flux = np.ones(len(jd))
    phase = ((jd - t0) % period) / period
    in_transit = (phase < duration/period/2) | (phase > 1 - duration/period/2)
    flux[in_transit] = 1 - depth
    flux += np.random.normal(0, 0.0005, len(flux))
    
    # Converti a magnitudini (normalizzate a mag=15)
    mag = 15 - 2.5 * np.log10(flux)
    
    # Salva
    with open('test_transit_mag.csv', 'w') as f:
        f.write("# Test Transit - Magnitudes only\n")
        f.write("JD, Magnitude\n")
        for j, m in zip(jd, mag):
            f.write(f"{j:.6f}, {m:.4f}\n")
    
    print("✓ File salvato: test_transit_mag.csv")
    print(f"  Formato: JD, Magnitude (2 colonne)")
    print(f"  Punti: {len(jd)}")
    print()